spike_team_setting:
    resource: "@SpikeTeamSettingBundle/Controller/"
    type:     annotation
    prefix:   /

spike_team_button:
    resource: "@SpikeTeamButtonBundle/Controller/"
    type:     annotation
    prefix:   /

spike_team_user:
    resource: "@SpikeTeamUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

spike_team_api:
    type: rest
    prefix: /api
    resource: "@SpikeTeamApiBundle/Resources/config/routing.yml"

spike_team_alert:
    resource:   "@SpikeTeamAlertBundle/Controller/"
    type:       annotation
    prefix:     /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
