spike_team_rest:
    resource: "@SpikeTeamRestBundle/Controller/"
    type:     annotation
    prefix:   /

spike_team_user:
    resource: "@SpikeTeamUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

rest:
    type: rest
    resource: "@SpikeTeamRestBundle/Resources/config/routing.yml"