security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        wsse_secured:
            pattern: ^/api/.*
            wsse:
                realm: "Secured API"
                profile: "UsernameToken"
                lifetime: 300
                encoder:
                    algorithm: sha1
            anonymous: false
            provider: fos_userbundle

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout: true
            anonymous: true

    access_control:
        - { path: ^/twilio, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
        - { path: ^/stats, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: POST }
        - { path: ^/, roles: ROLE_ADMIN, requires_channel: http }
        - { path: ^/api, roles: ROLE_API, requires_channel: http }