services:
    spike_team.listener.alert:
        class: SpikeTeam\AlertBundle\Event\AlertListener
        tags:
            - { name: kernel.event_listener, event: alert.send, method: onAlert }
        arguments: [@service_container]