services:
    spike_team.listener.alert:
        class: SpikeTeam\AlertBundle\Event\AlertListener
        tags:
            - { name: kernel.event_listener, event: alert.send, method: onAlert }
        arguments: ["@doctrine.orm.entity_manager", "@spike_team.notification_service"]
    spike_team.notification_service:
        class: SpikeTeam\AlertBundle\Services\NotificationService
        arguments: ["@doctrine.orm.entity_manager", "@router", %host%, %api_key%]