services:
    spike_team.user_helper:
        class: SpikeTeam\UserBundle\Helper\UserHelper
        arguments: ["@doctrine.orm.entity_manager"]
    spike_team.spiker_group_helper:
        class: SpikeTeam\UserBundle\Helper\SpikerGroupHelper
        arguments: ["@doctrine.orm.entity_manager"]